import type { Car } from '../model/types';

const PLACEHOLDER_IMAGE = 'https://placehold.co/800x600/f2f2ef/8c8c86?text=%20';

function createMockCar(overrides: Partial<Car> = {}): Car {
  return {
    id: '1',
    brand: 'BYD',
    model: 'E2',
    year: 2018,
    listingType: 'general',
    transmission: 'Автомат',
    fuelType: 'Электромобиль',
    carClass: 'Хэтчбек',
    countSeat: 5,
    pricePerDay: 150,
    currency: 'сомони',
    deposit: 1000,
    depositPerDay: 200,
    minRentDays: 3,
    workDays: 7,
    weekendDays: 0,
    images: [PLACEHOLDER_IMAGE, PLACEHOLDER_IMAGE, PLACEHOLDER_IMAGE],
    ...overrides,
  };
}

export const mockCars: Car[] = [
  createMockCar({
    id: '1',
    brand: 'Chevrolet',
    model: 'Cobalt',
    year: 2022,
    fuelType: 'Бензин',
    carClass: 'Седан',
    pricePerDay: 190,
    deposit: 1500,
    minRentDays: 3,
  }),
  createMockCar({
    id: '2',
    brand: 'Toyota',
    model: 'Camry',
    year: 2021,
    fuelType: 'Гибрид',
    carClass: 'Седан',
    pricePerDay: 340,
    deposit: 3000,
    minRentDays: 2,
  }),
  createMockCar({
    id: '3',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    fuelType: 'Дизель',
    carClass: 'Кроссовер',
    pricePerDay: 520,
    deposit: 0,
    minRentDays: 3,
  }),
  createMockCar({
    id: '4',
    brand: 'Chevrolet',
    model: 'Nexia',
    year: 2020,
    listingType: 'taxi',
    transmission: 'Механика',
    fuelType: 'Газ / бензин',
    carClass: 'Седан',
    pricePerDay: 150,
    workDays: 7,
    weekendDays: 3,
  }),
  createMockCar({
    id: '5',
    brand: 'Changan',
    model: 'Alsvin',
    year: 2022,
    transmission: 'Механика',
    fuelType: 'Бензин',
    carClass: 'Седан',
    pricePerDay: 200,
    deposit: 1500,
    minRentDays: 5,
  }),
  createMockCar({
    id: '6',
    brand: 'Geely',
    model: 'Emgrand',
    year: 2021,
    fuelType: 'Бензин',
    carClass: 'Седан',
    pricePerDay: 180,
    deposit: 1200,
    minRentDays: 3,
  }),
  createMockCar({
    id: '7',
    brand: 'Chery',
    model: 'Tiggo 4',
    year: 2023,
    fuelType: 'Бензин',
    carClass: 'Кроссовер',
    pricePerDay: 250,
    deposit: 2000,
    minRentDays: 2,
  }),
  createMockCar({
    id: '8',
    brand: 'Kia',
    model: 'Rio',
    year: 2020,
    listingType: 'taxi',
    fuelType: 'Бензин',
    carClass: 'Седан',
    pricePerDay: 165,
    workDays: 6,
    weekendDays: 1,
  }),
];
