/**
 * Все доступные имена иконок.
 *
 * Иконки из @ioyandasoz/io_ui_lib + кастомные для проекта.
 */
export type IconName =
  // --- Навигация ---
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-down'
  | 'chevron-up'
  | 'arrow-left'
  | 'arrow-right'
  | 'back'
  | 'expand'
  | 'external-link'
  | 'menu'
  | 'menu-down'
  | 'home'
  // --- Действия ---
  | 'x'
  | 'x-circle'
  | 'plus'
  | 'plus-circle'
  | 'minus'
  | 'minus-circle'
  | 'check'
  | 'edit'
  | 'delete'
  | 'save'
  | 'download'
  | 'export'
  | 'refresh'
  | 'copy'
  | 'link'
  | 'flip'
  | 'rotate'
  | 'drag'
  | 'subtract'
  // --- Фильтры ---
  | 'filter'
  | 'filter-edit'
  | 'filter-lines'
  | 'filter-plus'
  | 'filter-remove'
  | 'filter-table'
  | 'menu-filter'
  // --- Уведомления и статусы ---
  | 'bell'
  | 'status-alert'
  | 'status-check'
  | 'help'
  | 'info'
  | 'lightning'
  // --- Медиа ---
  | 'add-photo'
  | 'add-notes'
  // --- Объекты ---
  | 'car'
  | 'taxi'
  | 'plane'
  | 'geo'
  | 'add-location'
  | 'map-pin'
  | 'building'
  | 'tag'
  | 'settings'
  | 'phone'
  | 'mail'
  | 'calendar'
  | 'clock'
  | 'bookmark'
  | 'circle'
  | 'gift'
  | 'globe'
  | 'graph'
  | 'inbox'
  | 'list'
  | 'moon'
  | 'sun'
  | 'report'
  | 'person-edit'
  | 'sigma'
  | 'spinner'
  | 'sql'
  | 'square-edit'
  | 'count'
  | 'eye'
  | 'eye-off'
  | 'shield'
  | 'search'
  | 'heart'
  | 'star'
  | 'user'
  | 'share'
  | 'log-in'
  | 'log-out'
  | 'fuel'
  | 'gauge'
  | 'maximize'
  | 'taxipark';
